In [128]:
import pandas as pd
from urllib.parse import urlparse
import os.path
import re

In [129]:
df=pd.read_csv('urldata.csv')
df.head()

   Unnamed: 0                        url   label  result
0           0     https://www.google.com  benign       0
1           1    https://www.youtube.com  benign       0
2           2   https://www.facebook.com  benign       0
3           3      https://www.baidu.com  benign       0
4           4  https://www.wikipedia.org  benign       0

In [130]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450176 entries, 0 to 450175
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   url     450176 non-null  object
 1   label   450176 non-null  object
 2   result  450176 non-null  int64
dtypes: int64(1), object(2)
memory usage: 10.3+ MB

In [132]:
df["label"].value_counts()

label
benign       345738
malicious    104438
Name: count, dtype: int64

In [133]:
urldata=df

In [134]:
def get_hostname_length(url):
    try:
        url = url.replace('[.]', '.')
        parsed_url = urlparse(url)
        hostname_length = len(parsed_url.netloc)
        return hostname_length
    except Exception as e:
        print(f"Error parsing URL '{url}': {e}")
        return None  


def get_path_length(url):
    try:
        url = url.replace('[.]', '.')
        parsed_url = urlparse(url)
        path_length = len(parsed_url.path)
        return path_length
    except Exception as e:
        print(f"Error parsing URL '{url}': {e}")
        return None

In [135]:
urldata['hostname_length'] = urldata['url'].apply(get_hostname_length)

urldata['path_length'] = urldata['url'].apply(get_path_length)

In [136]:
def fd_length(url):
    url = url.replace('[.]', '.')
    urlpath= urlparse(url).path
    try:
        return len(urlpath.split('/')[1])
    except:
        return 0

urldata['fd_length'] = urldata['url'].apply(lambda i: fd_length(i))

In [137]:
urldata.head(10)

,url,label,result,hostname_length,path_length,fd_length
0,https://www.google.com,benign,0,14,0,0
1,https://www.youtube.com,benign,0,15,0,0
2,https://www.facebook.com,benign,0,16,0,0
3,https://www.baidu.com,benign,0,13,0,0
4,https://www.wikipedia.org,benign,0,17,0,0
5,https://www.reddit.com,benign,0,14,0,0
6,https://www.yahoo.com,benign,0,13,0,0
7,https://www.google.co.in,benign,0,16,0,0
8,https://www.qq.com,benign,0,10,0,0
9,https://www.amazon.com,benign,0,14,0,0

In [138]:
urldata['count-'] = urldata['url'].apply(lambda i: i.count('-'))

urldata['count@'] = urldata['url'].apply(lambda i: i.count('@'))

urldata['count?'] = urldata['url'].apply(lambda i: i.count('?'))

urldata['count%'] = urldata['url'].apply(lambda i: i.count('%'))

urldata['count.'] = urldata['url'].apply(lambda i: i.count('.'))

urldata['count='] = urldata['url'].apply(lambda i: i.count('='))

urldata['count-http'] = urldata['url'].apply(lambda i : i.count('http'))

urldata['count-https'] = urldata['url'].apply(lambda i : i.count('https'))

urldata['count-www'] = urldata['url'].apply(lambda i: i.count('www'))

In [139]:

def digit_count(url):
    digits = 0
    for i in url:
        if i.isnumeric():
            digits = digits + 1
    return digits
urldata['count-digits']= urldata['url'].apply(lambda i: digit_count(i))

In [140]:
def letter_count(url):
    letters = 0
    for i in url:
        if i.isalpha():
            letters = letters + 1
    return letters
urldata['count-letters']= urldata['url'].apply(lambda i: letter_count(i))

In [141]:
def no_of_dir(url):
    url = url.replace('[.]', '.')
    urldir = urlparse(url).path
    return urldir.count('/')
urldata['count_dir'] = urldata['url'].apply(lambda i: no_of_dir(i))

In [142]:
urldata.head()

,url,label,result,hostname_length,path_length,fd_length,count-,count@,count?,count%,count.,count=,count-http,count-https,count-www,count-digits,count-letters,count_dir
0,https://www.google.com,benign,0,14,0,0,0,0,0,0,2,0,1,1,1,0,17,0
1,https://www.youtube.com,benign,0,15,0,0,0,0,0,0,2,0,1,1,1,0,18,0
2,https://www.facebook.com,benign,0,16,0,0,0,0,0,0,2,0,1,1,1,0,19,0
3,https://www.baidu.com,benign,0,13,0,0,0,0,0,0,2,0,1,1,1,0,16,0
4,https://www.wikipedia.org,benign,0,17,0,0,0,0,0,0,2,0,1,1,1,0,20,0

In [143]:
def having_ip_address(url):
    match = re.search(
        '(([01]?\d\d?|2[0-4]\d|25[0-5])\.([01]?\d\d?|2[0-4]\d|25[0-5])\.([01]?\d\d?|2[0-4]\d|25[0-5])\.'
        '([01]?\d\d?|2[0-4]\d|25[0-5])\/)|' 
        '((0x[0-9a-fA-F]{1,2})\.(0x[0-9a-fA-F]{1,2})\.(0x[0-9a-fA-F]{1,2})\.(0x[0-9a-fA-F]{1,2})\/)' 
        '(?:[a-fA-F0-9]{1,4}:){7}[a-fA-F0-9]{1,4}', url) 
    if match:
        
        return -1
    else:
        
        return 1
urldata['use_of_ip'] = urldata['url'].apply(lambda i: having_ip_address(i))

In [144]:
urldata.head()

,url,label,result,hostname_length,path_length,fd_length,count-,count@,count?,count%,count.,count=,count-http,count-https,count-www,count-digits,count-letters,count_dir,use_of_ip
0,https://www.google.com,benign,0,14,0,0,0,0,0,0,2,0,1,1,1,0,17,0,1
1,https://www.youtube.com,benign,0,15,0,0,0,0,0,0,2,0,1,1,1,0,18,0,1
2,https://www.facebook.com,benign,0,16,0,0,0,0,0,0,2,0,1,1,1,0,19,0,1
3,https://www.baidu.com,benign,0,13,0,0,0,0,0,0,2,0,1,1,1,0,16,0,1
4,https://www.wikipedia.org,benign,0,17,0,0,0,0,0,0,2,0,1,1,1,0,20,0,1

In [145]:
urldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450176 entries, 0 to 450175
Data columns (total 19 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   url              450176 non-null  object
 1   label            450176 non-null  object
 2   result           450176 non-null  int64
 3   hostname_length  450176 non-null  int64
 4   path_length      450176 non-null  int64
 5   fd_length        450176 non-null  int64
 6   count-           450176 non-null  int64
 7   count@           450176 non-null  int64
 8   count?           450176 non-null  int64
 9   count%           450176 non-null  int64
 10  count.           450176 non-null  int64
 11  count=           450176 non-null  int64
 12  count-http       450176 non-null  int64
 13  count-https      450176 non-null  int64
 14  count-www        450176 non-null  int64
 15  count-digits     450176 non-null  int64
 16  count-letters    450176 non-null  int64
 17  count_dir        450176 non-null  int64
 18  use_of_ip        450176 non-null  int64
dtypes: int64(17), object(2)
memory usage: 65.3+ MB

In [146]:
urldata.to_csv("url_feature_extracted.csv")